name = "CMP"
author = "MakarenkoVlad"
version = "0.2.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6250ae74b2d03877b6d6d860438f88d3ee88a9d54f689bb57ceaae444bc6eeb7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
