name = "CMP"
author = "MakarenkoVlad"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d8a8bbded744aaace5ea73df78e14145894f6798e38533c346087bc1918b86c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
